import type {
  FeedbackEntry,
  Job,
  ShortlistItem,
  UncertaintyFlag,
} from "../types";

interface ClientPackInput {
  job: Job;
  shortlist: ShortlistItem[];
  borderline: ShortlistItem[];
  uncertaintyFlags: UncertaintyFlag[];
  feedback: FeedbackEntry[];
}

export function buildClientPackText(input: ClientPackInput): string {
  const { job, shortlist, borderline, uncertaintyFlags, feedback } = input;
  const lines: string[] = [
    "TALENTFLOW — CLIENT SUBMISSION PACK",
    "=".repeat(50),
    "",
    "ROLE DETAILS",
    `- Title: ${job.title}`,
    `- Department: ${job.department}`,
    `- Location: ${job.location}`,
    `- Level: ${job.level}`,
    `- Status: ${job.status}`,
    "",
    "RANKED SHORTLIST",
  ];

  if (shortlist.length === 0) {
    lines.push("No candidates evaluated yet.");
  } else {
    for (const item of shortlist) {
      lines.push(
        `[${item.rank}] ${item.name} — ${item.match_score}% — ${item.meets_bar ? "Meets bar" : "Below bar"}`,
      );
      lines.push(`    Reason: ${item.reason}`);
    }
  }

  lines.push("", "BORDERLINE CANDIDATES");
  if (borderline.length === 0) {
    lines.push("None.");
  } else {
    for (const item of borderline) {
      lines.push(`- ${item.name} — ${item.match_score}% — ${item.reason}`);
    }
  }

  lines.push("", "UNCERTAINTY FLAGS (HUMAN REVIEW)");
  if (uncertaintyFlags.length === 0) {
    lines.push("None.");
  } else {
    for (const flag of uncertaintyFlags) {
      lines.push(`- ${flag.candidate}: ${flag.issue}`);
      lines.push(`  Clarification: ${flag.clarification_needed}`);
    }
  }

  lines.push("", "RECRUITER FEEDBACK APPLIED");
  if (feedback.length === 0) {
    lines.push("None.");
  } else {
    for (const entry of feedback) {
      lines.push(`- ${entry.candidate_name}: ${entry.comment}`);
      if (entry.corrected_match_score != null) {
        lines.push(`  Corrected score: ${entry.corrected_match_score}%`);
      }
    }
  }

  lines.push(
    "",
    "---",
    `Generated by TalentFlow · ${new Date().toLocaleString()}`,
    "AI prepared this pack. Recruiter reviewed before client submission.",
  );

  return lines.join("\n");
}

export function downloadClientPack(input: ClientPackInput): void {
  const text = buildClientPackText(input);
  const slug = input.job.title.toLowerCase().replace(/[^a-z0-9]+/g, "-");
  const blob = new Blob([text], { type: "text/plain;charset=utf-8" });
  const url = URL.createObjectURL(blob);
  const anchor = document.createElement("a");
  anchor.href = url;
  anchor.download = `talentflow-client-pack-${slug}.txt`;
  anchor.click();
  URL.revokeObjectURL(url);
}
